supplements = [
  {"label": "L-Tyrosine", "bottle_size": 90, "bottle_cost": 24.11, "daily_dose": 1, "current_stock": 68},
  {"label": "Citicoline (CDP Choline)", "bottle_size": 120, "bottle_cost": 92.29, "daily_dose": 1, "current_stock": 117},
  {"label": "St Johns Wort", "bottle_size": 250, "bottle_cost": 39.97, "daily_dose": 3, "current_stock": 314},
  {"label": "Bacopa Extract", "bottle_size": 90, "bottle_cost": 36.88, "daily_dose": 1, "current_stock": 45},
  {"label": "Acetyl-L-Carnitine (ALCAR)", "bottle_size": 200, "bottle_cost": 65.21, "daily_dose": 2, "current_stock": 150},
  {"label": "Eye Armor", "bottle_size": 60, "bottle_cost": 69.95, "daily_dose": 1, "current_stock": 90},
  {"label": "Rhodiola Extract", "bottle_size": 60, "bottle_cost": 38.84, "daily_dose": 1, "current_stock": 63},
  {"label": "NAC (N-Acetyl Cysteine)", "bottle_size": 250, "bottle_cost": 56.88, "daily_dose": 2, "current_stock": 153},
  {"label": "BioActive Complete B-Complex", "bottle_size": 60, "bottle_cost": 16.96, "daily_dose": 2, "current_stock": 46},
  {"label": "Vitamin B6", "bottle_size": 100, "bottle_cost": 15.53, "daily_dose": 1, "current_stock": 117},
  {"label": "Pyridoxal 5'-Phosphate Caps", "bottle_size": 60, "bottle_cost": 26.79, "daily_dose": 2, "current_stock": 0},
  # {"label": "Pyridoxal 5'-Phosphate Caps", "bottle_size": 60, "bottle_cost": 22.68, "daily_dose": 4, "current_stock": 0},
  {"label": "Optimized Folate L-Methylfolate", "bottle_size": 100, "bottle_cost": 15.20, "daily_dose": 1, "current_stock": 55},
  {"label": "Vitamin B12", "bottle_size": 60, "bottle_cost": 12.18, "daily_dose": 1, "current_stock": 30},
  {"label": "L-OptiZinc", "bottle_size": 100, "bottle_cost": 12.68, "daily_dose": 1, "current_stock": 55},
  {"label": "Vitamin D-3", "bottle_size": 240, "bottle_cost": 21.86, "daily_dose": 1, "current_stock": 54},
  {"label": "DHA-500", "bottle_size": 90, "bottle_cost": 35.21, "daily_dose": 2, "current_stock": 0},
  {"label": "Magnesium Malate", "bottle_size": 180, "bottle_cost": 27.65, "daily_dose": 3, "current_stock": 0},
  {"label": "SAMe", "bottle_size": 60, "bottle_cost": 82.42, "daily_dose": 1, "current_stock": 37},
  # {"label": "Complete Afterbiotics", "bottle_size": 30, "bottle_cost": 62.42, "daily_dose": 1, "current_stock": 5},
]
